In [2]:
import numpy as np

np.__version__

'2.0.2'

In [3]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [5]:
arr_list1 = np.array(list1)
print(arr_list1)
print(type(arr_list1))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# creating 3-dim array using 3 lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]

arr_list1_3 = np.array([[list1, list2, list3]])
print(arr_list1_3)
print(arr_list1_3.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3




#### 2. numpy array attributes

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
# Attributes of Array (properties of array)
print("Shape", arr1.shape)  # share= rows, columns and height of array
print("Size", arr1.size)    # number of elements in array
print("dType", arr1.dtype)  # data type of elements in array
print("n_dim", arr1.ndim)   # dimension of array

[[1 2 3]
 [4 5 6]]
Shape (2, 3)
Size 6
dType int64
n_dim 2


#### 3. Array initialization methods

In [15]:
# zeros array : all elements are 0

zero_arr = np.zeros((2,3))
print(zero_arr)

# ones array : all elements are 1

one_arr = np.ones((1,3))
print(one_arr)

# Full array : all elements are same based on given value

full_arr = np.full((3,2), 9)
print(full_arr)

# Identity Matrix : diagonal elements are ones and all other elements are zeros

id_arr = np.eye(3)
print(id_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:

# empty array
print(np.empty(2))

[1.5e-323 1.5e-323]


In [17]:
# evenly spaced array : elements are evenly spaced based on step value
print(np.arange(2,10,2))

[2 4 6 8]


In [18]:
# specific number of eqaully spaced values between a range : elements are equally spaced based on step value
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [19]:
# random values array - float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.77882793 0.70505461]
 [0.20509753 0.08480085]
 [0.8070804  0.94848698]]


In [20]:
# random values array - int
rint_arr = np.random.randint(1,100,(3,3))
print(rint_arr)

[[ 1 69 87]
 [33 38 47]
 [72 86 90]]


#### 4 Array Indexing and Slicing






In [21]:
import numpy as np

print("=" * 50)
print("BASIC INDEXING")
print("=" * 50)

# 1D array
arr1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1d)
print("Element at index 2:", arr1d[2])           # 30
print("Element at index -1:", arr1d[-1])         # 50
print("Element at index -2:", arr1d[-2])         # 40

# 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\n2D Array:\n", arr2d)
print("Element at (1, 2):", arr2d[1, 2])         # 6
print("Element at (2, 0):", arr2d[2, 0])         # 7
print("Element at (0, -1):", arr2d[0, -1])       # 3

# 3D array
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print("\n3D Array shape:", arr3d.shape)
print("Element at (1, 0, 1):", arr3d[1, 0, 1])   # 6

print("\n" + "=" * 50)
print("1D ARRAY SLICING")
print("=" * 50)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array:", arr)

# Basic slicing: [start:stop:step]
print("\nBasic Slicing:")
print("arr[2:5]:", arr[2:5])                     # [2, 3, 4]
print("arr[:5]:", arr[:5])                       # [0, 1, 2, 3, 4]
print("arr[5:]:", arr[5:])                       # [5, 6, 7, 8, 9]
print("arr[::2]:", arr[::2])                     # [0, 2, 4, 6, 8] (every 2nd)
print("arr[1::2]:", arr[1::2])                   # [1, 3, 5, 7, 9]
print("arr[::-1]:", arr[::-1])                   # Reverse array

print("\nNegative indices in slicing:")
print("arr[-5:]:", arr[-5:])                     # Last 5 elements
print("arr[:-3]:", arr[:-3])                     # All except last 3
print("arr[-6:-2]:", arr[-6:-2])                 # From 6th last to 2nd last

print("\n" + "=" * 50)
print("2D ARRAY SLICING")
print("=" * 50)

arr2d = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])
print("2D Array (4x5):\n", arr2d)

print("\nRow Slicing:")
print("First 2 rows:\n", arr2d[:2])              # Rows 0-1
print("Rows 1 to 3:\n", arr2d[1:3])              # Rows 1-2
print("Every other row:\n", arr2d[::2])          # Rows 0, 2

print("\nColumn Slicing:")
print("First 3 columns:\n", arr2d[:, :3])        # All rows, cols 0-2
print("Last 2 columns:\n", arr2d[:, -2:])        # All rows, last 2 cols
print("Columns 1 to 4:\n", arr2d[:, 1:4])        # All rows, cols 1-3
print("Every other column:\n", arr2d[:, ::2])    # Cols 0, 2, 4

print("\nCombined Row and Column Slicing:")
print("Rows 1-3, cols 2-4:\n", arr2d[1:3, 2:4])  # Submatrix
print("First 2 rows, last 3 cols:\n", arr2d[:2, -3:])
print("Every other row, every 3rd col:\n", arr2d[::2, ::3])

print("\n" + "=" * 50)
print("3D ARRAY SLICING")
print("=" * 50)

arr3d = np.arange(24).reshape(2, 3, 4)
print("3D Array shape (2, 3, 4):\n", arr3d)

print("\nSlicing 3D arrays:")
print("First element of each 2D slice:\n", arr3d[:, 0, 0])
print("First row of each 2D slice:\n", arr3d[:, 0, :])
print("First 2D slice, all rows, first 2 cols:\n", arr3d[0, :, :2])

print("\n" + "=" * 50)
print("FANCY INDEXING")
print("=" * 50)

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Array:", arr)

# Indexing with integer arrays
indices = np.array([2, 5, 7])
print("\nIndexing with array [2, 5, 7]:", arr[indices])  # [30, 60, 80]

# Multiple arrays for multi-dimensional indexing
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
rows = np.array([0, 1, 2])
cols = np.array([0, 1, 2])
print("\nDiagonal elements using fancy indexing:", arr2d[rows, cols])  # [1, 5, 9]

# Boolean indexing
print("\nBoolean Indexing:")
print("Elements > 25:", arr[arr > 25])
print("Elements between 30 and 70:", arr[(arr > 30) & (arr < 70)])
print("Elements that are 20 or 80:", arr[(arr == 20) | (arr == 80)])
print("Elements NOT 50:", arr[arr != 50])

print("\n" + "=" * 50)
print("MODIFYING ARRAYS WITH INDEXING")
print("=" * 50)

arr = np.arange(10)
print("Original array:", arr)

arr[3] = 100
print("After arr[3] = 100:", arr)

arr[5:8] = 999
print("After arr[5:8] = 999:", arr)

arr[arr < 5] = -1
print("After arr[arr < 5] = -1:", arr)

# Broadcasting with assignment
arr2d = np.zeros((3, 4))
print("\n2D array before:\n", arr2d)
arr2d[1, :] = 5           # Set second row to 5
arr2d[:, 2] = 3           # Set third column to 3
print("\n2D array after modifications:\n", arr2d)

print("\n" + "=" * 50)
print("VIEWS VS COPIES")
print("=" * 50)

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Creating a view (shares memory)
view = arr[1:4]
view[0] = 999
print("After modifying view[0] = 999:")
print("Original array:", arr)    # Changed!
print("View:", view)

# Creating a copy (separate memory)
arr = np.array([1, 2, 3, 4, 5])
copy = arr[1:4].copy()
copy[0] = 888
print("\nAfter modifying copy[0] = 888:")
print("Original array:", arr)    # Unchanged
print("Copy:", copy)

print("\n" + "=" * 50)
print("PRACTICAL EXAMPLES")
print("=" * 50)

# Example 1: Extracting specific patterns
matrix = np.arange(25).reshape(5, 5)
print("5x5 matrix:\n", matrix)

print("\nExtracting corners:")
corners = matrix[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corners (top-left, top-right, bottom-left, bottom-right):", corners)

print("\nExtracting border elements (without corners):")
top_border = matrix[0, 1:-1]
bottom_border = matrix[-1, 1:-1]
left_border = matrix[1:-1, 0]
right_border = matrix[1:-1, -1]
print("Top border:", top_border)
print("Bottom border:", bottom_border)
print("Left border:", left_border)
print("Right border:", right_border)

# Example 2: Selecting based on conditions
data = np.random.randint(0, 100, 20)
print("\nRandom data:", data)
print("Values between 25 and 75:", data[(data >= 25) & (data <= 75)])
print("Indices where value > 50:", np.where(data > 50)[0])

# Example 3: Structured data selection
students = np.array([('Alice', 85, 90),
                     ('Bob', 75, 80),
                     ('Charlie', 95, 92)],
                    dtype=[('name', 'U10'), ('math', 'i4'), ('science', 'i4')])

print("\nStudents with math > 80:")
print(students[students['math'] > 80])

print("\n" + "=" * 50)
print("ADVANCED INDEXING TECHNIQUES")
print("=" * 50)

# ix_ function for grid indexing
arr = np.arange(10).reshape(2, 5)
print("Array:\n", arr)

rows = np.array([0, 1])
cols = np.array([1, 3])
print("\nUsing ix_ for grid indexing:")
print("arr[np.ix_(rows, cols)]:\n", arr[np.ix_(rows, cols)])

# take and put functions
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 3, 4]
print("\nUsing take():", np.take(arr, indices))
print("Using take with mode='clip':", np.take(arr, [0, 10, -5], mode='clip'))
print("Using take with mode='wrap':", np.take(arr, [0, 10, -5], mode='wrap'))

# put function
arr = np.array([1, 2, 3, 4, 5])
np.put(arr, [0, 2, 4], [10, 30, 50])
print("\nAfter put([0,2,4], [10,30,50]):", arr)

# select function
x = np.arange(10)
conditions = [x < 3, x > 7]
choices = [x**2, x**3]
result = np.select(conditions, choices, default=x)
print("\nUsing select() for piecewise function:", result)

print("\n" + "=" * 50)
print("MEMORY LAYOUT AND STRIDES")
print("=" * 50)

arr = np.arange(12).reshape(3, 4)
print("Array:\n", arr)
print("Strides:", arr.strides)  # (32, 8) for int64: row jump=32 bytes, column jump=8 bytes
print("Flags:\n", arr.flags)

# Transpose creates a view with different strides
transposed = arr.T
print("\nTransposed array:\n", transposed)
print("Transposed strides:", transposed.strides)

print("\n" + "=" * 50)
print("COMMON PITFALLS AND TIPS")
print("=" * 50)

# Pitfall 1: Modifying slices affects original
arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]
slice_view[:] = 0
print("Pitfall 1 - After slice_view[:] = 0:")
print("Original array:", arr)  # Changed!

# Solution: Use .copy()
arr = np.array([1, 2, 3, 4, 5])
slice_copy = arr[1:4].copy()
slice_copy[:] = 0
print("\nSolution using .copy():")
print("Original array:", arr)  # Unchanged

# Pitfall 2: Boolean indexing creates copy
arr = np.array([1, 2, 3, 4, 5])
subset = arr[arr > 2]
subset[0] = 999
print("\nPitfall 2 - Boolean indexing creates copy:")
print("Original array:", arr)  # Unchanged

# Tip: Use np.where for in-place modification
arr = np.array([1, 2, 3, 4, 5])
arr[np.where(arr > 2)] = 999
print("\nTip: Using np.where for in-place modification:")
print("Modified array:", arr)

BASIC INDEXING
1D Array: [10 20 30 40 50]
Element at index 2: 30
Element at index -1: 50
Element at index -2: 40

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6
Element at (2, 0): 7
Element at (0, -1): 3

3D Array shape: (2, 2, 2)
Element at (1, 0, 1): 6

1D ARRAY SLICING
Array: [0 1 2 3 4 5 6 7 8 9]

Basic Slicing:
arr[2:5]: [2 3 4]
arr[:5]: [0 1 2 3 4]
arr[5:]: [5 6 7 8 9]
arr[::2]: [0 2 4 6 8]
arr[1::2]: [1 3 5 7 9]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]

Negative indices in slicing:
arr[-5:]: [5 6 7 8 9]
arr[:-3]: [0 1 2 3 4 5 6]
arr[-6:-2]: [4 5 6 7]

2D ARRAY SLICING
2D Array (4x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Row Slicing:
First 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Rows 1 to 3:
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]
Every other row:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]]

Column Slicing:
First 3 columns:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
Last 2 columns:
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
Columns 1 to 

#### 5 Array Reshaping and Flattening

In [22]:
import numpy as np

# Create 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping (change dimensions, data stays same)
reshaped_2d = arr.reshape(2, 3)
reshaped_3d = arr.reshape(1, 2, 3)

# Flattening (convert to 1D)
flattened = reshaped_2d.flatten()
raveled = reshaped_2d.ravel()

# Printing results
print("Original 1D array:\n", arr)
print("\nReshaped to 2x3:\n", reshaped_2d)
print("\nReshaped to 1x2x3:\n", reshaped_3d)
print("\nFlatten using flatten():\n", flattened)
print("\nFlatten using ravel():\n", raveled)


Original 1D array:
 [1 2 3 4 5 6]

Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]

Reshaped to 1x2x3:
 [[[1 2 3]
  [4 5 6]]]

Flatten using flatten():
 [1 2 3 4 5 6]

Flatten using ravel():
 [1 2 3 4 5 6]


#### 6 Array Stacking and Splitting

In [23]:
# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# ---------- STACKING ----------
# Vertical stacking (row-wise)
v_stack = np.vstack((a, b))

# Horizontal stacking (column-wise)
h_stack = np.hstack((a, b))

# General stacking (new axis)
stack_0 = np.stack((a, b), axis=0)
stack_1 = np.stack((a, b), axis=1)

# ---------- SPLITTING ----------
# Split 1D array
arr = np.array([10, 20, 30, 40, 50, 60])

split_equal = np.split(arr, 3)        # equal parts
split_custom = np.array_split(arr, 4) # unequal parts allowed

# Split 2D array
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

h_split = np.hsplit(arr2d, 2)  # column-wise split
v_split = np.vsplit(arr2d, 2)  # row-wise split

# ---------- OUTPUT ----------
print("Vertical Stack:\n", v_stack)
print("\nHorizontal Stack:\n", h_stack)
print("\nStack axis=0:\n", stack_0)
print("\nStack axis=1:\n", stack_1)

print("\nSplit equally:", split_equal)
print("Split custom:", split_custom)

print("\nHorizontal Split:\n", h_split)
print("\nVertical Split:\n", v_split)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]

Horizontal Stack:
 [1 2 3 4 5 6]

Stack axis=0:
 [[1 2 3]
 [4 5 6]]

Stack axis=1:
 [[1 4]
 [2 5]
 [3 6]]

Split equally: [array([10, 20]), array([30, 40]), array([50, 60])]
Split custom: [array([10, 20]), array([30, 40]), array([50]), array([60])]

Horizontal Split:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

Vertical Split:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


#### 7 Mathematical Operations on Array

In [24]:
import numpy as np

# Create arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# ---------- BASIC ARITHMETIC ----------
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** b)

# ---------- AGGREGATE FUNCTIONS ----------
print("\nSum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard Deviation:", np.std(a))

# ---------- ELEMENT-WISE FUNCTIONS ----------
print("\nSquare Root:", np.sqrt(a))
print("Exponential:", np.exp(b))
print("Log:", np.log(a))

# ---------- TRIGONOMETRIC ----------
angles = np.array([0, 30, 45, 90])
radians = np.deg2rad(angles)

print("\nSin:", np.sin(radians))
print("Cos:", np.cos(radians))
print("Tan:", np.tan(radians))


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Power: [   10   400 27000]

Sum: 60
Mean: 20.0
Max: 30
Min: 10
Standard Deviation: 8.16496580927726

Square Root: [3.16227766 4.47213595 5.47722558]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Log: [2.30258509 2.99573227 3.40119738]

Sin: [0.         0.5        0.70710678 1.        ]
Cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 6.12323400e-17]
Tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.63312394e+16]


#### 8 Mathematical Operations on Muliple Arrays




In [25]:
import numpy as np

# Create multiple 1D arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
c = np.array([2, 2, 2])

# -------- ELEMENT-WISE OPERATIONS --------
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)

# -------- OPERATIONS WITH MORE THAN TWO ARRAYS --------
print("\n(a + b) * c =", (a + b) * c)
print("a * b + c =", a * b + c)

# -------- NUMPY FUNCTIONS ON MULTIPLE ARRAYS --------
print("\nMaximum of a and b =", np.maximum(a, b))
print("Minimum of a and b =", np.minimum(a, b))

# -------- DOT PRODUCT --------
print("\nDot product of a and b =", np.dot(a, b))

# -------- COMPARISON OPERATIONS --------
print("\na > b =", a > b)
print("a == c =", a == c)

# -------- 2D ARRAY OPERATIONS --------
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

print("\n2D Array Addition:\n", x + y)
print("\n2D Matrix Multiplication:\n", np.dot(x, y))


a + b = [11 22 33]
a - b = [ 9 18 27]
a * b = [10 40 90]
a / b = [10. 10. 10.]

(a + b) * c = [22 44 66]
a * b + c = [12 42 92]

Maximum of a and b = [10 20 30]
Minimum of a and b = [1 2 3]

Dot product of a and b = 140

a > b = [ True  True  True]
a == c = [False False False]

2D Array Addition:
 [[ 6  8]
 [10 12]]

2D Matrix Multiplication:
 [[19 22]
 [43 50]]


#### 9 Statistical Functions

In [26]:
import numpy as np

# Create array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# -------- BASIC STATISTICS --------
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Range (max-min):", np.ptp(arr))

# -------- AXIS-WISE STATISTICS --------
print("\nSum (column-wise):", np.sum(arr, axis=0))
print("Sum (row-wise):", np.sum(arr, axis=1))

print("\nMean (column-wise):", np.mean(arr, axis=0))
print("Mean (row-wise):", np.mean(arr, axis=1))

# -------- VARIANCE & STD --------
print("\nVariance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

# -------- PERCENTILES --------
print("\n25th Percentile:", np.percentile(arr, 25))
print("50th Percentile (Median):", np.percentile(arr, 50))
print("75th Percentile:", np.percentile(arr, 75))


Sum: 210
Mean: 35.0
Median: 35.0
Minimum: 10
Maximum: 60
Range (max-min): 50

Sum (column-wise): [50 70 90]
Sum (row-wise): [ 60 150]

Mean (column-wise): [25. 35. 45.]
Mean (row-wise): [20. 50.]

Variance: 291.6666666666667
Standard Deviation: 17.07825127659933

25th Percentile: 22.5
50th Percentile (Median): 35.0
75th Percentile: 47.5


#### 11 Broadcasting

In [27]:
import numpy as np

# ============================================================================
# 1. WHAT IS BROADCASTING?
# ============================================================================
print("1. BROADCASTING BASICS")
print("-" * 40)

"""
Broadcasting = Operations on arrays of different shapes
No data copying - virtual expansion
"""

# Example: Array + Scalar
arr = np.array([[1, 2], [3, 4]])
print("Array + 10:\n", arr + 10)

# ============================================================================
# 2. BROADCASTING RULES
# ============================================================================
print("\n2. BROADCASTING RULES")
print("-" * 40)

"""
Rules:
1. Compare shapes from RIGHT
2. Dimensions must:
   - Be equal, OR
   - One is 1
"""

# Works: (3,4) + (4,)
A = np.ones((3, 4))
B = np.array([1, 2, 3, 4])
print("(3,4) + (4,) works:\n", A + B)

# Fails: (3,4) + (3,)
try:
    C = np.array([1, 2, 3])
    A + C
except ValueError as e:
    print(f"(3,4) + (3,) fails: {e}")

# ============================================================================
# 3. COMMON PATTERNS
# ============================================================================
print("\n3. COMMON PATTERNS")
print("-" * 40)

# Pattern 1: Normalization
data = np.random.randn(100, 5)
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
print("Data normalized (mean=0, std=1)")

# Pattern 2: Outer product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
outer = a[:, None] * b  # (3,1) * (3,) → (3,3)
print("\nOuter product:\n", outer)

# Pattern 3: Add bias (ML)
activations = np.random.rand(32, 64)  # batch=32, neurons=64
bias = np.random.rand(64)
result = activations + bias  # bias added to each sample
print(f"\nAdd bias: {activations.shape} + {bias.shape} = {result.shape}")

# ============================================================================
# 4. USEFUL FUNCTIONS
# ============================================================================
print("\n4. USEFUL FUNCTIONS")
print("-" * 40)

# Add dimensions
arr = np.array([1, 2, 3])
print("Original shape:", arr.shape)
print("Row vector:", arr[np.newaxis, :].shape)    # (1, 3)
print("Column vector:", arr[:, np.newaxis].shape) # (3, 1)

# Check broadcast shapes
print("\nBroadcast checks:")
print("(3,4) + (4,) →", np.broadcast_shapes((3,4), (4,)))
print("(2,1,3) + (3,) →", np.broadcast_shapes((2,1,3), (3,)))

# Force broadcasting
arr = np.array([1, 2, 3])
print("\nForce broadcast to (3,3):")
print(np.broadcast_to(arr, (3, 3)))

# ============================================================================
# 5. PRACTICAL EXAMPLES
# ============================================================================
print("\n5. PRACTICAL EXAMPLES")
print("-" * 40)

# Image processing
image = np.random.randint(0, 256, (5, 5, 3), dtype=np.uint8)
brightness_boost = np.array([1.2, 1.0, 0.8])  # RGB adjustments
brightened = np.clip(image * brightness_boost, 0, 255).astype(np.uint8)
print(f"Image brightened: {image.shape} * {brightness_boost.shape}")

# Distance matrix
points = np.array([[1, 2], [3, 4], [5, 6]])
# Efficient pairwise distances using broadcasting
diff = points[:, None, :] - points[None, :, :]
distances = np.sqrt(np.sum(diff**2, axis=-1))
print(f"\nPairwise distances ({points.shape[0]} points):\n", distances)

# ============================================================================
# 6. PERFORMANCE TIPS
# ============================================================================
print("\n6. PERFORMANCE TIPS")
print("-" * 40)

"""
1. Use broadcasting instead of loops
2. Avoid unnecessary np.newaxis
3. Check shapes before operations
4. Use np.broadcast_shapes() for debugging
"""

# Bad: Python loop
size = 10000
arr1 = np.random.rand(size)
arr2 = np.random.rand(size)
result_slow = np.zeros(size)
for i in range(size):
    result_slow[i] = arr1[i] + arr2[i]

# Good: Broadcasting
result_fast = arr1 + arr2

print("Broadcasting is MUCH faster than loops")
print(f"Same result: {np.allclose(result_slow, result_fast)}")

# ============================================================================
# 7. QUICK REFERENCE
# ============================================================================
print("\n7. QUICK REFERENCE")
print("-" * 40)

print("""
WORKING CASES:
  (3,4) + (4,)      ✓  # Add to each row
  (3,4) + (3,1)     ✓  # Add to each column
  (3,1,4) + (1,2,1) ✓  # Complex broadcast

FAILING CASES:
  (3,4) + (3,)      ✗  # Incompatible
  (2,3) + (3,2)     ✗  # Neither 1 nor equal

COMMON USES:
  • Normalization: (data - mean) / std
  • ML layers: X @ W + bias
  • Image filters: image * filter
  • Pairwise operations

KEY FUNCTIONS:
  arr[:, None]      # Add column dimension
  arr[None, :]      # Add row dimension
  np.broadcast_shapes()  # Check compatibility
  np.broadcast_to()      # Explicit broadcast
""")

1. BROADCASTING BASICS
----------------------------------------
Array + 10:
 [[11 12]
 [13 14]]

2. BROADCASTING RULES
----------------------------------------
(3,4) + (4,) works:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
(3,4) + (3,) fails: operands could not be broadcast together with shapes (3,4) (3,) 

3. COMMON PATTERNS
----------------------------------------
Data normalized (mean=0, std=1)

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Add bias: (32, 64) + (64,) = (32, 64)

4. USEFUL FUNCTIONS
----------------------------------------
Original shape: (3,)
Row vector: (1, 3)
Column vector: (3, 1)

Broadcast checks:
(3,4) + (4,) → (3, 4)
(2,1,3) + (3,) → (2, 1, 3)

Force broadcast to (3,3):
[[1 2 3]
 [1 2 3]
 [1 2 3]]

5. PRACTICAL EXAMPLES
----------------------------------------
Image brightened: (5, 5, 3) * (3,)

Pairwise distances (3 points):
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]

6. PERFORMANC

#### 12 Handling with nan & inf

In [30]:
import numpy as np

# 1. Create NaN & Inf
arr = np.array([1.0, np.nan, np.inf, 5.0])
print("Original:", arr)

# 2. Check for NaN/Inf
print("isnan:", np.isnan(arr))
print("isinf:", np.isinf(arr))
print("isfinite:", np.isfinite(arr))

# 3. Calculations ignoring NaN
data = np.array([1, 2, np.nan, 4, 5])
print("nanmean:", np.nanmean(data))
print("nansum:", np.nansum(data))

# 4. Replace NaN
arr = np.array([1.0, np.nan, 3.0, np.nan])
# Method 1
arr_fixed = np.where(np.isnan(arr), 0, arr)
print("Replace with 0:", arr_fixed)

# Method 2
arr_filled = np.nan_to_num(arr, nan=-1)
print("Replace with -1:", arr_filled)

# 5. Remove NaN values
clean = arr[~np.isnan(arr)]
print("Clean array:", clean)

# 6. Important: NaN comparison
nan_val = np.nan
print(f"np.nan == np.nan: {nan_val == nan_val}")  # False!
print(f"np.isnan(np.nan): {np.isnan(nan_val)}")   # True

# 7. Real example
temps = np.array([22.5, np.nan, 23.1, np.nan, 24.0, 22.8])
# Fill missing temps with mean
mean_temp = np.nanmean(temps)
temps_filled = np.where(np.isnan(temps), mean_temp, temps)
print("Filled temps:", temps_filled)

Original: [ 1. nan inf  5.]
isnan: [False  True False False]
isinf: [False False  True False]
isfinite: [ True False False  True]
nanmean: 3.0
nansum: 12.0
Replace with 0: [1. 0. 3. 0.]
Replace with -1: [ 1. -1.  3. -1.]
Clean array: [1. 3.]
np.nan == np.nan: False
np.isnan(np.nan): True
Filled temps: [22.5 23.1 23.1 23.1 24.  22.8]
