##Arrays

In [ ]:
#0-d array
import numpy as np
arr = np.array(5)
print(arr)
type(arr)

5


numpy.ndarray

In [ ]:
#1-d array
arr = np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


In [ ]:
#2d array
#formed when we combine a lot of 1d arrays
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#3d array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


##Accessing array

In [ ]:
#accessing array in 1d array
arr = np.array([1,2,3,4,5])
print(f"in 2d array the element is {arr[2]}")

#accessing array in 2d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"in 2d array the element is {arr[1,3]}")

#accessing arrays in 3d array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(f"in 3d array the element is {arr[2,0,2]}")


in 2d array the element is 3
in 2d array the element is 9
in 3d array the element is 15


#Slicing Array

In [ ]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[1,0:,1:3])# accessing 12 ,13, 17, 18

[[12 13]
 [17 18]]


In [ ]:
# To check number of dimensions of array we use ndim
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
arr.ndim


3

In [ ]:
# To change data type of array we use .astype
arr = np.array([1.1,2.2,1.3,1.4,100.5])
new_arr = arr.astype("int")
print(new_arr)
new_arr = arr.astype("str")
print(new_arr)

#To check datatype of array we use .dtype
print(arr.dtype)
print(new_arr.dtype)





[  1   2   1   1 100]
['1.1' '2.2' '1.3' '1.4' '100.5']
float64
<U32


copy vs view function

In [ ]:
arr= np.array([1,2,3,4,5])
new_arr = arr.copy()
new_arr[0]=10
print(f"new arr is {new_arr}")
print(f"old arr is {arr}") #copy

new arr is [10  2  3  4  5]
old arr is [1 2 3 4 5]


In [ ]:
arr= np.array([1,2,3,4,5])
new_arr = arr.view()
new_arr[0]=10
print(f"new arr is {new_arr}")
print(f"old arr is {arr}") #view

new arr is [10  2  3  4  5]
old arr is [10  2  3  4  5]


Checking array shape

In [ ]:
#using ndim
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr.ndim

3

In [ ]:
#using arr.shape
arr.shape

(3, 2, 3)

In [ ]:
#using array reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)
print("..")
new_arr = arr.reshape(2,3,2)
print(new_arr)
print(new_arr.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
..
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr1 = new_arr.reshape(1,-1)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Looping into arrays


In [ ]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
for i in new_arr:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#nditer (used for printing single element)
for i in np.nditer(new_arr):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


Sorting array

In [ ]:
arr = np.array([1,2,3,4,5,10,4])
arr
new_arr=np.sort(arr)
print(new_arr)

[ 1  2  3  4  4  5 10]


In [ ]:
#for doing it in descending order
np.arr=np.sort(new_arr)[::-1]
np.arr

array([10,  5,  4,  4,  3,  2,  1])

Array Search

In [ ]:
#where method

In [ ]:
arr


array([ 1,  2,  3,  4,  5, 10,  4])

In [ ]:
x = np.where(arr==4)
x

(array([3, 6]),)

In [ ]:
#using where to find indexing of even number
arr_neww= np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(arr_neww % 2 == 0)
print(x)


(array([1, 3, 5, 7, 9]),)


In [ ]:
##searchsorted
arr_neww= np.array([1,2,3,4,5,6,100,8,9,10])
np.searchsorted(arr_neww, 11)

10

Array Filter

In [ ]:
arr = np.array([41,42,43,44])
arr

array([41, 42, 43, 44])

In [ ]:
x = [True,False,True,False]
x

[True, False, True, False]

In [ ]:
new_arr = arr[x]
new_arr

array([41, 43])

In [ ]:
##Practical
arr = np.array([41,42,43,44])
x = []
for i in arr:
  if i%2==0:
    x.append(True)
  else:
    x.append(False)

print(x)
new_arr = arr[x]
print(new_arr)


[False, True, False, True]
[42 44]


Random Number


In [ ]:
from numpy import random


In [ ]:
x = random.randint(100)
x

44

In [ ]:
x = random.randint(1,25,size=(5,5))
print(x)


[[21  1 22 11 20]
 [ 5 18 16  3 19]
 [21 13 18  2 16]
 [11 10 20 10 10]
 [ 3 17 18 12 16]]


Joining Arrays

In [ ]:
#Concatination
arr1 = np.array([[41,42,43,44],[22,23,34,22]])
arr2 = np.array([[34,55,100,44],[22,99,11,22]])
print(np.concatenate((arr1,arr2), axis=1))
print(".....")
print(np.concatenate((arr1,arr2), axis=0))



[[ 41  42  43  44  34  55 100  44]
 [ 22  23  34  22  22  99  11  22]]
.....
[[ 41  42  43  44]
 [ 22  23  34  22]
 [ 34  55 100  44]
 [ 22  99  11  22]]


In [ ]:
#Stacking
#it increases axis by one unit
arr1

array([[41, 42, 43, 44],
       [22, 23, 34, 22]])

In [ ]:
arr2

array([[ 34,  55, 100,  44],
       [ 22,  99,  11,  22]])

In [ ]:
a= np.stack((arr1,arr2), axis=0)
print(f"using stacking the new array is {a}")
print(f"the dimension of new array is {arr1.ndim}")

using stacking the new array is [[[ 41  42  43  44]
  [ 22  23  34  22]]

 [[ 34  55 100  44]
  [ 22  99  11  22]]]
the dimension of new array is 2


spilliting array

In [ ]:
#array_split

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
new_arr = np.array_split(arr,3) # stores inside list
print(new_arr)
print(new_arr[0])
print(new_arr[1])



[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
