In [63]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)
#2d and 3d
b = np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1 2 3
[5 2 3 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(type(c))
print(c)
print(b)

<class 'numpy.ndarray'>
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
[[1 2 3]
 [4 5 6]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,3))

array([[0.06338574, 0.15264865, 0.81934706],
       [0.26883289, 0.17204692, 0.16909303],
       [0.43420581, 0.394624  , 0.79297634]])

In [ ]:
np.linspace(0, 100, 5)


array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(-10, 10, 10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
a1 = np.arange(10, dtype=np.float32)
a2 = np.arange(12, dtype=np.int32).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a1.ndim
print(a1.ndim)
a2.ndim
print(a2.ndim)
a3.ndim
print(a3.ndim)


1
2
3


In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.itemsize

4

In [ ]:
#dtype
print(a3.dtype)
print(a1.dtype)
print(a2.dtype)

int64
float32
int32


In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
# scalar operation
a1 ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)

In [ ]:
a2 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [ ]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)
print(a1)


[[0.07332972 0.39610033 0.35207393]
 [0.46200744 0.0025533  0.21442334]
 [0.28505308 0.85655629 0.72019208]]


In [ ]:
#max/min/sum/prod
print(a2.max())
print(a2.min())
print(a2.sum())
print(a2.prod())

86.0
0.0
336.0
0.0


In [ ]:
print(np.max(a1, axis=0)) #0 is row
print(np.max(a1, axis=1))  #1 is column

[0.46200744 0.85655629 0.72019208]
[0.39610033 0.46200744 0.85655629]


In [ ]:
# mean/mode/median/sd/var
print(np.mean(a1, axis=1))
print(np.median(a1, axis=0))
print(np.std(a1))
print(np.var(a1))

[0.27383466 0.22632803 0.62060048]
[0.28505308 0.39610033 0.35207393]
0.2631379061116919
0.06924155763284559


In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[0.07326402, 0.38582355, 0.34484526],
       [0.44574599, 0.0025533 , 0.21278401],
       [0.28120839, 0.75559127, 0.65952907]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[1.07608528, 1.4860184 , 1.42201365],
       [1.58725712, 1.00255656, 1.23914712],
       [1.32983261, 2.35503664, 2.05482787]])

In [ ]:
# round/floor /ceil
print(np.round(np.random.random((2,3))*100))
np.ceil(np.random.random((2,3))*100)

[[54. 19.  3.]
 [92. 69. 83.]]


array([[53., 25., 11.],
       [53.,  1., 20.]])

In [4]:
# slicing and indexing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [11]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1,0]

4

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3[1,0,1]

5

In [16]:
a3[0,1,0]

2

In [17]:
a3[0,0,0]

0

In [18]:
a3[1,1,0]

6

In [19]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1[2:5]

array([2, 3, 4])

In [21]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2[0,:]

array([0, 1, 2, 3])

In [25]:
a2[:,2]

array([ 2,  6, 10])

In [31]:
a2[1:,1:3:]

array([[ 5,  6],
       [ 9, 10]])

In [33]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [34]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [36]:
a2[1,::3]

array([4, 7])

In [37]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [39]:
# 3D array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [43]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
a3[0,1]

array([3, 4, 5])

In [41]:
a3[1,1,1]

13

In [45]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [46]:
#Iterating

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
#reshaping


In [53]:
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [54]:
#Ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [57]:
#stacking
  #horiontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [60]:
#stacking
  #horiontal stacking
print(np.hstack((a4,a5)))
print("")
   #vertical stacking
print(np.vstack((a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [61]:
#splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [66]:
np.vsplit(a4,2)

ValueError: array split does not result in an equal division